GoogleCloudPlatform/blueprints

- catalog/empty/Kptfile
- catalog/empty/README.md
- catalog/empty/noop.yaml
The empty blueprint contains a `local-config` config map
to work around an issue. This will be removed in the near future.
> An empty blueprint

- catalog/networking/network/subnet/setters.yaml
This is a better workaround for https://github.com/GoogleCloudPlatform/blueprints/issues/28 which prevents duplication.
Fixes #28.
> fix: only specify immediate setters in subnet setters.yaml

- utils/kpt-list-setters.sh
example usage:
```
$ utils/kpt-list-setters.sh catalog/gitops/ -c
Setter           Usages
cluster-name     9
configsync-dir   1
deployment-repo  4
namespace        10
project-id       16
project-number   2
source-repo      5
```
> Add utils/list-setters.sh

- utils/add-attribution.sh
- utils/fix-attribution.sh
Limitations:
1. Requires at least kpt v1.0.0-beta.2
1. kpt fn grep was removed and there's no replacement to only edit certain files with functions.
1. kpt fn sink doesn't support updating existing directories, so I had to use kpt fn eval instead
1. kpt drops single quotes around strings: https://github.com/GoogleContainerTools/kpt/issues/2383
Replaces https://github.com/GoogleCloudPlatform/blueprints/pull/54
> Update add-attribribution and add fix-attribution.sh

- utils/component-versions.sh
```
$ ./utils/component-versions.sh 
Config Controller: 0.0.727
ConfigSync: v1.8.0-rc.8
Gatekeeper: anthos1.6.1-5610c59.g0
Config Connector: 1.55.0
Cork: N/A
```
Useful for debugging and customer bug reports.
Hopefully eventually superseded by b/179427625
> Add component-versions.sh

- catalog/gitops/hydration-trigger.yaml
For the initial build, `config/*` may not match any files leading to `fatal: pathspec '/deployment-workspace/config/*' did not match any files`. This adds ` --ignore-unmatch` flag so exit code will still be zero.
> fix: gitops hydration trigger

- catalog/gitops/README.md
- catalog/gitops/cloudbuild-iam.yaml
- catalog/gitops/configsync/README.md
- catalog/gitops/configsync/configsync-iam.yaml
- catalog/landing-zone/README.md
- catalog/landing-zone/iam.yaml
- catalog/landing-zone/namespaces/hierarchy.yaml
- catalog/landing-zone/namespaces/logging.yaml
- catalog/landing-zone/namespaces/networking.yaml
- catalog/landing-zone/namespaces/policies.yaml
- catalog/landing-zone/namespaces/projects.yaml
- catalog/log-export/org/bigquery-export/README.md
- catalog/log-export/org/bigquery-export/iam.yaml
- catalog/project/kcc-namespace/README.md
Switching the blueprints to use IAMPartialPolicy, where possible, instead of IAMPolicyMember.
A few places that use memberRef instead of member could not be converted as IAMPartialPolicy does not support memberRef.
> Switch to using IAMPartialPolicy instead of IAMPolicyMember

- catalog/project/kcc-namespace/Kptfile
- catalog/project/kcc-namespace/validation.yaml
Adds validation in the project namespace blueprint to ensure that given projects ns is different from tenant project-id
> fix: add validation for project ns blueprint

- .prow.yaml
Surfaced in validation tests added via https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1269
> chore: fix prow config for timeout

- catalog/gitops/hydration-trigger.yaml
Updates the function name/image to: [gcr.io/kpt-fn/remove-local-config-resources:v0.1](https://catalog.kpt.dev/remove-local-config-resources/v0.1/)
> fix: updates function name for remove-annotated-resources

- catalog/iam-foundation/Kptfile
- catalog/iam-foundation/README.md
- catalog/iam-foundation/devops.yaml
- catalog/iam-foundation/networking.yaml
- catalog/iam-foundation/org.yaml
- catalog/iam-foundation/security.yaml
- catalog/iam-foundation/setters.yaml
Extracts the foundational IAM blueprint into its own package which can be used independently or as part of a larger landing zone.
> feat: Add foundational IAM blueprint

- catalog/landing-zone-lite/Kptfile
- catalog/landing-zone-lite/README.md
- catalog/landing-zone-lite/iam.yaml
- catalog/landing-zone-lite/namespaces/hierarchy.yaml
- catalog/landing-zone-lite/namespaces/projects.yaml
- catalog/landing-zone-lite/services.yaml
- catalog/landing-zone-lite/setters.yaml
- catalog/landing-zone/Kptfile
- catalog/landing-zone/README.md
- catalog/landing-zone/services.yaml
Implement landing-zone-lite and fix some issues in the existing LZ blueprints
1. landing-zone-lite blueprint contains only hierarchy and projects; no logging, networking or policies
2. Add necessary service enablements needed to make certain GCP APIs work (serviceusage + resourcemanager)
3. Add an projectIAMAdmin policy to the organization for projects-sa so that it can update and manage IAM policies on the corresponding projects that are created
> Implement landing-zone-lite and fix some issues in the existing LZ blueprints

- .release-please-manifest.json
https://github.com/GoogleCloudPlatform/blueprints/pull/82 PR was created bumping iam-foundation blueprint to 0.2.0 as the initial version was set to 0.1.0. This makes the initial version `0.0.1` for release-please to create `0.1.0` release in PR.
> chore: fix iam-foundation initial version

- catalog/acm/acm-membership-api.yaml
- catalog/acm/config-mgmt-csr.yaml
- catalog/acm/config-mgmt-iam.yaml
- catalog/acm/feat-config-mgmt.yaml
- catalog/acm/membership.yaml
- catalog/acm/services.yaml
I noticed the setters and actual values in configuration had diverged. This renders config with the setter defaults.
> fix: use setter defaults in ACM config

- release-please-config.json
release-please ignores commits before previous release PR #82 and is ignoring #83 and #87 commit messages prefixed with `feat:` for calculating new release semver. This PR should force release-please to release as a specified version to work around this.
> chore: explicit release as for acm and anthos-cluster

- catalog/landing-zone-lite/iam.yaml
- catalog/landing-zone-lite/namespaces/hierarchy.yaml
- catalog/landing-zone-lite/namespaces/projects.yaml
- catalog/landing-zone-lite/services.yaml
Workaround for https://github.com/GoogleCloudPlatform/blueprints/issues/121 to unblock release. This PR sets the correct attribution.
> fix: add correct attribution for lz lite

- release-please-config.json
This removed explicit release-as added for release please to force release as 0.1.0 in https://github.com/GoogleCloudPlatform/blueprints/pull/117 now that 0.1.0 releases exist.
> chore: remove bootstrap release-as

- catalog/gitops/hydration-trigger.yaml
Update kpt to version kpt:v1.0.0-beta.9.
Using the current version with the landing-zone blueprint fails with the following error for the workspace package:
Package "workspace": 
error: resources must be annotated with config.kubernetes.io/index to be written to files
Upgrading to this version solved the issue.
> fix: bump kpt version in hydration pipeline

- catalog/project/kcc-namespace/kcc.yaml
The resourceRef already covers this.
> fix: remove redundant project annotation from IAMPartialPolicy

- catalog/bucket/README.md
- catalog/bucket/bucket.yaml
- catalog/bucket/setters.yaml
- catalog/redis-bucket/README.md
- catalog/redis-bucket/bucket.yaml
- catalog/redis-bucket/redis.yaml
- catalog/redis-bucket/setters.yaml
Also make sure they use `config-control` as the default namespace.
> fix: remove namespace setters from bucket and redis blueprints

- catalog/gke-autopilot/cluster/cluster.yaml
- catalog/gke-autopilot/cluster/container-api.yaml
Since GKE autopilot is a single package I don't think colon delimited `gke-autopilot` adds value.
> fix: GKE autopilot attribution

- catalog/gke/README.md
- catalog/gke/cluster/README.md
- catalog/gke/cluster/cluster.yaml
- catalog/gke/cluster/container-api.yaml
- catalog/gke/cluster/setters.yaml
- catalog/gke/nodepools/primary/README.md
- catalog/gke/nodepools/primary/node-iam.yaml
- catalog/gke/nodepools/primary/nodepool.yaml
- catalog/gke/nodepools/primary/setters.yaml
- catalog/gke/setters.yaml
Remove setters for
- project-id
- namespace
set-project-id function needs to be run imperatively e.g.:
`kpt fn eval --include-meta-resources --image gcr.io/kpt-fn/set-project-id:v0.2.0 -- 'project-id=$PROJECT_ID'`
Before `kpt fn render`
> fix: reduce setters for GKE blueprint

- catalog/networking/svpc-service-project/README.md
- catalog/networking/svpc-service-project/serviceproject.yaml
- catalog/networking/svpc-service-project/setters.yaml
Use separate setters for project and networking namespaces when
attaching shared vpc service projects. This blueprint needs to make a
project reference and also allow the networking service account with
xpnAdmin permissions to be used.
> Set separate project & networking namespaces

- catalog/landing-zone/namespaces/hierarchy.yaml
- catalog/landing-zone/namespaces/logging.yaml
- catalog/landing-zone/namespaces/networking.yaml
- catalog/landing-zone/namespaces/policies.yaml
- catalog/landing-zone/namespaces/projects.yaml
These resources are necessary for least-privilege on Config Controller, but are not useful in clusterless mode.
> fix: ignore namespace IAM resources in clusterless mode

- catalog/gitops/configsync/config-management.yaml
Looks like this `syncRevision` field should have been `syncRev` per https://cloud.google.com/anthos-config-management/docs/configmanagement-fields#configuring-git-repo. 
`syncRev` defaults to `HEAD` so I don't think there is value in keeping it in config.
```
error: error validating "gitops/configsync/config-management.yaml": error validating data: ValidationError(ConfigManagement.spec.git): unknown field "syncRevision" in io.gke.configmanagement.v1.ConfigManagement.spec.git; if you choose to ignore these errors, turn validation off with --validate=false
```
> fix: remove gitops ConfigManagement syncRevision field

- catalog/log-export/folder/storage-export/export.yaml
- catalog/log-export/org/storage-export/export.yaml
This sets a default one year retention policy for the log export buckets. Optionally retention lock can be enabled for users with stricter compliance requirements.
> feat: add one year retention policy to log export buckets

- examples/iam-audit-config/Kptfile
- examples/iam-audit-config/README.md
- examples/iam-audit-config/audit.yaml
- examples/iam-audit-config/setters.yaml
Adds an example showing how to configure org level IAMAuditConfig similar to [example-foundation](https://github.com/terraform-google-modules/terraform-example-foundation/blob/8391f1bd4322fec04fda7509b537c5f66cddbbd9/1-org/envs/shared/iam.tf#L25-L44)
> chore: add IAMAuditConfig example

- catalog/log-export/folder/storage-export/README.md
- catalog/log-export/folder/storage-export/export.yaml
- catalog/log-export/folder/storage-export/setters.yaml
- catalog/log-export/org/storage-export/README.md
- catalog/log-export/org/storage-export/export.yaml
- catalog/log-export/org/storage-export/setters.yaml
This also aligns with TF blueprint defaults 
https://github.com/terraform-google-modules/terraform-google-log-export/blob/86d638817306fad77e4756c116ceea976cedb567/modules/storage/variables.tf#L50-L54
> fix!: replace bucket policy in storage log export with uniform bucket level access

- catalog/gitops/configsync/README.md
- catalog/gitops/configsync/config-management.yaml
- catalog/gitops/configsync/configsync-iam.yaml
- catalog/gitops/configsync/rootsync.yaml
Update gitops blueprint to use multirepo mode. Marking as draft until 1.11 rolls out in CC
> feat: gitops multirepo update

- catalog/gitops/configsync/Kptfile
- catalog/gitops/configsync/README.md
- catalog/gitops/configsync/validation.yaml
* Limits cluster-name to 25 character for maximum service account ID length
* Update README with cluster-name length
* Add validator for cluster-name-length, displays cluster-name length on failure
b/241421051
> feat: add cluster-name validator, update README

- .github/workflows/schema.yml
- .prow.yaml
- Makefile
- catalog/landing-zone/services.yaml
- examples/dual-svpc/vpc-shared-restricted/vpcsc-perimeter/perimeter.yaml
- utils/lint.sh
This adds schema validation for all KRM blueprints and examples by applying CRDs to a kind cluster and performing server side dry run apply. Some other fixes include
- remove include meta flag which is not used in newer kpt versions
- found an invalid schema in one of the examples which was fixed
There were some complexities getting kind to work inside a prow pod and after discussing with engprod, I switched CI for lint to GHA as we don't need any auth.
b/255631955 and go/fs-automated-validation
> chore: add KRM schema validation

- utils/lint.sh
--include-meta-resources is no longer necessary because meta resources are now included by default
> chore: remove --include-meta-resources

- catalog/anthos-cluster/acm/README.md
- catalog/anthos-cluster/acm/config-mgmt-csr.yaml
- catalog/anthos-cluster/acm/setters.yaml
Remove setter for
* acm-version 
The latest version of ACM will be used, however users can in-place edit if needed.
Fixes #196
> fix: reduce setters for ACM on GKE blueprint
